---
# tasks file for r role

- name: Set distribution include file fact
  set_fact:
    linux_distro: "{% if ansible_distribution == 'Ubuntu' %}ubuntu.yml{% elif ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora' %}rhel.yml{% elif ansible_os_family == 'Suse' %}suse.yml{% endif %}"
  tags:
    - r-install

- name: Create list of all R versions
  set_fact:
    all_r_versions: "{{ [r_version] + r_version_alt }}"

- name: "Include {{ linux_distro }} tasks"
  include_tasks: "{{ linux_distro }}"
  tags:
    - r-install

- name: Verify R installation
  command: "/opt/R/{{ r_version }}/bin/R --version"
  register: r_version_output
  changed_when: false
  failed_when: false
  tags:
    - r-install
    - r-install-verify

- name: Display R version
  debug:
    msg: "R {{ r_version }} installation status: {{ 'SUCCESS' if r_version_output.rc == 0 else 'FAILED' }}"
  tags:
    - r-install
    - r-install-verify