---
# RHEL-specific tasks for R installation
- name: Set RHEL version-specific variables
  set_fact:
    r_base_url: "{% if ansible_distribution_major_version == '8' %}https://cdn.rstudio.com/r/centos-8/pkgs{% elif ansible_distribution_major_version == '9' %}https://cdn.rstudio.com/r/rhel-9/pkgs{% endif %}"
  tags:
    - r-install

- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present
  tags:
    - r-install

- name: "Enable CodeReady Linux Builder repository (RHEL {{ ansible_distribution_major_version }})"
  command: "dnf config-manager --set-enabled codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-*-rpms"
  when: ansible_distribution_major_version == "9" || ansible_distribution_major_version == "8"
  changed_when: false
  tags:
    - r-install

- name: "Enable EPEL repository for RHEL{{ ansible_distribution_major_version }}"
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"  
    state: present
    disable_gpg_check: true
  when: ansible_distribution_major_version == "8" || ansible_distribution_major_version == "9"
  tags:
    - r-install

- name: "Download R packages for {{ item }}"
  get_url:
    url: "{{ r_base_url }}/R-{{ item }}-1-1.x86_64.rpm"
    dest: "/tmp/R-{{ item }}-1-1.x86_64.rpm"
    mode: '0644'
  loop: "{{ all_r_versions }}"
  tags:
    - r-install

- name: "Install R for {{ item }}"
  yum:
    name: "/tmp/R-{{ item }}-1-1.x86_64.rpm"
    state: present
    disable_gpg_check: yes
  loop: "{{ all_r_versions }}"
  tags:
    - r-install

# Clean up downloaded packages
- name: "Clean up downloaded R for {{ item }}"
  file:
    path: "/tmp/R-{{ item }}-1-1.x86_64.rpm"
    state: absent
  loop: "{{ all_r_versions }}"
  tags:
    - r-install

- name: Create symlinks for primary R version (add to system PATH)
  file:
    src: "/opt/R/{{ r_version }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: yes
  loop:
    - R
    - Rscript
  tags:
    - r-install